### PR TITLE
Automatic GFBANM hash generation from GFBANMCFG content of a GFPAK

### PR DESCRIPTION
**Pull request by HelloOO7**
This minor edit to GFPAK.cs does the following to benefit navigation of GFPAK archives without a complete hash cache:

- Changes the file load sequence to first load all entries before processing them.
- Adds a loop through the archive entries between the loading and processing loops that reads all GFBANMCFG files, retrieves the FileName parameters from those and adds them to the local hash table.

Some notes:

- It might save up CPU power and load times to remove the animation strings from Pkmn.txt which should be safe to do now that they are generated recursively from the archive.
- On the contrary, if the hash list in Pkmn.txt was made into a static field, it'd possibly save a good chunk of RAM by not hashing the whole Pkmn.txt per-archive and could possibly accelerate the loading even further by making the entire GFPAK hash list static, having the animation hashes stored for the entire lifetime of a given Toolbox instance.
- Please, please, please, please *fix your code*. Seriously, this thing is full of oversights, unhandled edge cases, confusing code arrangement/sequencing (why do I have to call like 4 different methods just to open a GFBANM programatically?) and could really use a code cleanup. It's one thing making a great juggernaut tool that leverages just about every C# game format library available in a user-friendly GUI and it's another that said tool is a pain to contribute to as someone else than the original author. This took like 10 minutes to write, which is not much, but would've been way less with a more navigatable codebase.

Oh and as always, a demo:
obrazek

I've tested this on character and Pokémon animations with results as expected.

### CODE REVIEW

**Comment by KillzXGaming** [comment]
The hash list should be a static field, seems I accidentally never set it. I also think it might be best to actually save calculated hashes into a binary on disc then load off that. 

The codebase yeah it's a hell of a mess (I have a new rewritten codebase called Toolbox.Core, but the UI side of things hasn't been finished). Alot of things are also being split into new, more polished up libraries but I haven't done the gf file formats yet (need to setup an in tool flat buffer parser/writer).

**Comment by HelloOO7** [comment]
Okay, I'm thinking about implementing the file cache, a couple of questions though:

- Should the format be fully readable as plain text? Potentially, the hashes could be saved alongside the names, eliminating the need for run-time hashing. A binary file with the hashes written as ULongs would probably be faster than a text file read with Long.parseLong (or whatever C# has for it), though it might not be a noticeable difference and I'm just over-engineering it.
- Another option is to use a binary cache and have a separate .txt for user-defined hashes that will get merged and cleared every time the hash list is requested.
- Or I can just not save the hashes alongside the names altogether. Dunno how fast FNV hashing is but the performance boost gained *might* as well be negligible.

Good luck with the flatbuffer parser, IMO they are the stupidest thing ever to choose for a graphics format, especially since GF has had a history of perfectly working binary-XML based formats that they just threw out of the window. Like, can you even iterate over a FB vector with foreach..?

**Comment by KillzXGaming** [comment]
I'd have both a normal string list and a binary file (strings and hashes) which gets saved for the first time. Then maybe some sort of checksum saved to the binary to compare newly added hashes to update the cache.

**Comment by HelloOO7** [comment]
Okay, now the question is, where to store the user-defined hashes? I'm not too familiar with your coding rules but I think using AppData is quite user-unfriendly so I'd naturally store something like Pkmn-user.txt in the root of the Toolbox directory, but I don't know if you don't have something against cluttering it like this. Also as for the checksum - well that's basically hashing it again, isn't it? I'd probably merge the user hashes to the binary on load and clear it, but that *could* be error-prone.
Also one last idea to optimize the speed even further - the hash cache binary could be sorted in ascending order of the FNV hash value, making binary search (or possibly another fast search algorithm) possible, but again, not sure how much faster that is.

**Comment by HelloOO7** [comment]
Alright, so I did some working title implementation that stores the cache into Hashes/GFPAKHashCache.bin in the Toolbox root directory and allows for loading user hashes from Hashes/GFPAK.txt in the same folder. The base hash cache is forcefully rebuilt whenever the Version.txt of Toolbox is changed, while the user cache is built on the first GFPAK load of each Toolbox start-up. It turned out to be a more efficient way than checking for HasValue on the dictionary for each of them, probably because ulongs are way faster to search for than strings. Hashes generated procedurally from Pokémon archives and animation configs are stored into the cache as they are discovered and aren't recalculated at all.
Is this eligible to be merged at this state?

**Comment by KillzXGaming** [comment]
LGTM, should be good to merge.

**Pull request merged**
