### PR TITLE
Updated Tegra X1 swizzling and nutexb block heights

### PR DESCRIPTION
**Pull request by ScanMountGoat**
# Tegra X1 Swizzling Rework
This PR completely reworks block linear swizzling and deswizzling, so I would recommend doing some additional testing before merging. Pitch linear remains unchanged. There are two main changes described below. Both of these changes have already been applied to Cross Mod. If you have any questions about the implementation changes, please let me know.

## tegra_swizzle.dll
The block linear swizzle/deswizzle functions have been completely rewritten in Rust. This gives a noticeable speed improvement in addition to improved correctness. The Rust implementation has been tested against non power of two texture dimensions, odd texture sizes, bpp values larger than 16, etc. In addition, the implementation has been tested using randomized testing to test stability and for testing that swizzle, deswizzle, swizzle works as expected. The code can be found here: https://github.com/ScanMountGoat/nutexb_swizzle. 

tegra_swizzle.dll doesn't allow block heights not supported by the Tegra TRM. Please let me know if you need this limitation removed in the future. I just restrict block height to the valid values of 1, 2, 4, 8, 16, or 32 for now rather than raise an exception.

## GetBlockHeight(heightInBytes, mipLevel)
The block height function has been reworked to fit experimental data for nutexb textures. You can find the up to date values here: https://github.com/ScanMountGoat/nutexb_swizzle/blob/main/nutexb_block_heights.csv. Block height is not a function of height when considering different mip levels. This is the cause of many of the issues such as Pyra's 320x320 BC7 textures not swizzling/deswizzling correctly. I'd like to come up with a more satisfying solution in the future, but fitting two step functions will give pretty accurate results given how many textures and mip levels have been tested.

### CODE REVIEW

**Comment by aboood40091** [comment]
Interesting findings.
I have long forgotten about the tiling algorithm since it just worked in the cases I needed it for and I just lost interest in the Switch, so I never had plans to improve it, but I may look more into this in the future since it's been getting some attention.

**Comment by gdkchan** [comment]
This is how the driver (and the GPU) calculates the GOB height for a given level:
```cs
static int GetMipBlockHeight(int baseHeight, int blockWidth, int blockHeight, int gobHeight, int level)
{
    int levelHeight = Math.Max(1, baseHeight >> level);
    int heightInBlocks = (levelHeight + (blockHeight - 1)) / blockHeight; // Divide rounding up.

    while (heightInBlocks <= (gobHeight / 2) * 8 && gobHeight > 1)
    {
        gobHeight /= 2;
    }

    return gobHeight;
}
```
Where:
`baseHeight` is the height of the texture for mip level 0.
`blockWidth` is the block width for compressed formats, should be 1 for non-compressed formats.
`blockHeight` is identical to the above but height.
`gobHeight` Is the height in GOBs of mip level 0 (`BlockHeight0` in your table).
`level` is the mip level you want to get the GOB height for.
The function will return `BlockHeightN` where `N` is the `level` you specified.

I believe their goal making it behave like this is avoid wasting memory by requiring at least more than half of the texture to fit the GOB. The `8` on the above function comes from the amount of lines per GOB, which is always 8. The size of a GOB is always 64x8 bytes, and the `BlockHeightN` is the amount of GOBs in the Y direction. So `BlockHeightN * 8` would be the height of the texture after being GOB aligned.

BTW, the function on the TRM will only work for 2D textures. For 3D texture, you also need to take the GOB depth into account, which is similar to the height one but in the Z direction. For completness sake, here's the function to get the mip gob depth for 3D textures:
```cs
static int GetMipBlockDepth(int baseDepth, int gobDepth, int level)
{
    int levelDepth = Math.Max(1, baseDepth >> level);

    while (levelDepth <= gobDepth / 2 && gobDepth > 1)
    {
        gobDepth /= 2;
    }

    return gobDepth;
}
```

Also, for array textures, there's an additional alignment between layers that you also need to take into account. The function below can calculate the aligned size given a non-aligned size:
```cs
static int AlignLayerSize(
    int size,
    int height,
    int depth,
    int blockHeight,
    int gobHeight,
    int gobDepth,
    int gobBlocksInTileX)
{
    if (gobBlocksInTileX < 2)
    {
        height = (height + (blockHeight - 1)) / blockHeight;

        while (height <= (gobHeight / 2) * 8 && gobHeight > 1)
        {
            gobHeight /= 2;
        }

        while (depth <= (gobDepth  / 2) && gobDepth > 1)
        {
            gobDepth /= 2;
        }

        int blockOfGobsSize = gobHeight * gobDepth * 512;
        int sizeInBlockOfGobs = size / blockOfGobsSize;

        if (size != sizeInBlockOfGobs * blockOfGobsSize)
        {
            size = (sizeInBlockOfGobs + 1) * blockOfGobsSize;
        }
    }
    else
    {
        int alignment = (gobBlocksInTileX * 512) * gobHeight * gobDepth;

        size = (size + (alignment - 1)) & ~(alignment - 1);
    }

    return size;
}
```
512 is the size of a GOB in bytes (64 * 8 = 512). `gobBlocksInTileX` is only used for sparse textures I believe, you might be able to assume it's always 1.

And just for completness sake, here's how the driver calculates a optimal GOB height if the user does not specify one:
```cs
static int GetOptimalBlockHeight(int height)
{
    int heightAndHalf = height + (height / 2);
    if (heightAndHalf >= 128)
    {
        return 16;
    }
    else if (heightAndHalf >= 64)
    {
        return 8;
    }
    else if (heightAndHalf >= 32)
    {
        return 4;
    }
    else if (heightAndHalf >= 16)
    {
        return 2;
    }
    else
    {
        return 1;
    }
}
```
It never uses a GOB size of 32, not sure why.

All the functions above were written based on reverse engineering of the Switch NVN driver code, so they should be all correct. I've been reversing their driver for quite some time for emulation, so if there's something else you want to know about the tiling or some other GPU related issue feel free to ask.

**Comment by ScanMountGoat** [comment]
block_heights
Thank you so much for posting that @gdkchan. The block height functions (lines) match up with the observations I had (points) for nutexb file mipmaps. 

I'll definitely be looking into supporting 3d textures and arrays in my Rust implementation in the future. After glancing at Ryujinx's implementation, it looks like I can keep my inner loop the same and just add the appropriate calculations for z like you mentioned.

**Comment by ScanMountGoat** [comment]
I've pushed the changes with the update functions for calculating the block heights. I plan on investigating arrays and 3d textures more in the future. The C# code now contains a link to the Rust source repo, which I forgot to include earlier.

**Pull request merged**
